apiVersion: v1
kind: Secret
metadata:
  name: add-learningcenter-label-for-certinjection
  namespace: tap-install
stringData:
  add-learningcenter-label-for-certinjection.yaml: |
    #@ load("@ytt:overlay", "overlay")
    
    #@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "cert-injection-webhook"}})
    ---
    spec:
      template:
        spec:
          containers:
          #@overlay/match by="name"
          - name: server
            args:
            #@overlay/append
            - -label=learningcenter.tanzu.vmware.com/session.name
