#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test
spec:
  params:
  - name: source-url
    type: string
  - name: source-revision
    type: string
  tasks:
  #@ if hasattr(data.values, "php"):
    #@ if data.values.php.enabled == "true":
  - name: test-coverage
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    taskSpec:
      metadata: {}
      params:
      - name: source-url
        type: string
      - name: source-revision
        type: string
      spec: null
      steps:
      - name: test
        #@ image = "composer:latest"
        #@ if hasattr(data.values.php, "test_image"):
        #@ image = data.values.php.test_image
        #@ end
        image: #@ image
        resources: {}
        script: |-
          set -ex
          whoami
          cd `mktemp -d`
          export HOME=$PWD
          export PATH=$HOME/.local/bin:$PATH

          wget -qO- $(params.source-url) | tar xvz -m
          composer install
          ./vendor/bin/phpunit
    #@ end
  #@ else:
  - name: test
    taskSpec:
      steps:
        - name: test
          image: ghcr.io/openzipkin/alpine:3.18.0
          script: |-
            echo hello
  #@ end
---
apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
kind: ScanPolicy
metadata:
  name: scan-policy
spec:
  regoFile: |
    package main

    deny[msg] {
    	false
    	msg = "dummy"
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-editor
  annotations:
    kapp.k14s.io/change-group: "sa"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-editor-bindings
  annotations:
    kapp.k14s.io/change-group: "sa"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-editor
subjects:
  - kind: ServiceAccount
    name: app-editor
---
apiVersion: v1
kind: Secret
metadata:
  name: app-editor-token
  annotations:
    kubernetes.io/service-account.name: app-editor
    kapp.k14s.io/change-rule: "upsert after upserting sa"
type: kubernetes.io/service-account-token

